#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Apr 29 18:14:51 PDT 2025
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim sim_test_behav -key {Behavioral:sim_1:Functional:sim_test} -tclbatch sim_test.tcl -protoinst "protoinst_files/clk_setup.protoinst" -view /home/ethan/Documents/ee119c/Class_D_Amp_2025/src/class_d_amplifier/sim_test_behav.wcfg -log simulate.log"
xsim sim_test_behav -key {Behavioral:sim_1:Functional:sim_test} -tclbatch sim_test.tcl -protoinst "protoinst_files/clk_setup.protoinst" -view /home/ethan/Documents/ee119c/Class_D_Amp_2025/src/class_d_amplifier/sim_test_behav.wcfg -log simulate.log

