set_property SRC_FILE_INFO {cfile:/home/ethan/Documents/ee119c/Class_D_Amp_2025/src/class_d_amplifier/class_d_amplifier.srcs/constrs_1/new/constraints.xdc rfile:../../../class_d_amplifier.srcs/constrs_1/new/constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clk_setup_i/CLK_MGR_0/inst/BCLK -source [get_pins clk_setup_i/clk_wiz_0/inst/mmcm_adv_inst/CLKOUT0] -divide_by 32 [get_pins clk_setup_i/CLK_MGR_0/inst/BCLK_reg/Q]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clk_setup_i/CLK_MGR_0/inst/WS -source [get_pins clk_setup_i/clk_wiz_0/inst/mmcm_adv_inst/CLKOUT0] -divide_by 1024 [get_pins clk_setup_i/CLK_MGR_0/inst/WS_reg/Q]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports EN]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N14 [get_ports CLK]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P4 [get_ports DI]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N3 [get_ports BCK]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N1 [get_ports WS]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P6 [get_ports RST]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property DRIVE 12 [get_ports EN]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW SLOW [get_ports EN]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T4 [get_ports EN]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M2 [get_ports EN_L]
