# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/clk_setup/clk_setup.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_setup || ORIG_REF_NAME==clk_setup} -quiet] -quiet

# IP: bd/clk_setup/ip/clk_setup_clk_wiz_0_0/clk_setup_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_setup_clk_wiz_0_0 || ORIG_REF_NAME==clk_setup_clk_wiz_0_0} -quiet] -quiet

# IP: bd/clk_setup/ip/clk_setup_I2S_interconnect_0_0/clk_setup_I2S_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_setup_I2S_interconnect_0_0 || ORIG_REF_NAME==clk_setup_I2S_interconnect_0_0} -quiet] -quiet

# IP: bd/clk_setup/ip/clk_setup_PWM_output_0_1/clk_setup_PWM_output_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_setup_PWM_output_0_1 || ORIG_REF_NAME==clk_setup_PWM_output_0_1} -quiet] -quiet

# IP: bd/clk_setup/ip/clk_setup_PWM_output_0_2/clk_setup_PWM_output_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_setup_PWM_output_0_2 || ORIG_REF_NAME==clk_setup_PWM_output_0_2} -quiet] -quiet

# IP: bd/clk_setup/ip/clk_setup_Quantizer_Interconne_0_0/clk_setup_Quantizer_Interconne_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_setup_Quantizer_Interconne_0_0 || ORIG_REF_NAME==clk_setup_Quantizer_Interconne_0_0} -quiet] -quiet

# XDC: /home/ethan/Documents/ee119c/Class_D_Amp_2025/src/class_d_amplifier/class_d_amplifier.gen/sources_1/bd/clk_setup/clk_setup_ooc.xdc
